version: '3.7'
services:
  json-server:
    build:
      dockerfile: Dockerfile
      context: ./json-server
    ports:
      - '3000:3000'
    volumes:
      - ./json-server/db.json:/data/db.json
    command: json-server --watch db.json --host 0.0.0.0
  front-end:
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - '5000:5000'
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    depends_on:
      - json-server
